### ISSUE TITLE
best slit spacing and 3rd order spectrum for 400mm f/2 scope

### ISSUE THREAD

**Issue by skyjak** [satakagi/tribahtinovWebApps#2]
Hi Satoru, I would like to create a TriBahtinov-Bahtinov mask for a C8 (whose native focal length is 2000mm) with HyperStar, which produces an effective focal length of 400mm. By using your drawing app, the slits come out very thin (using a Bahtinov ratio of 100).  But if I check "Use 3rd order spectrum", then the slits become quite wider.  So my question is: what is the 3rd order spectrum?  and should I use that option to draw the optimal TriBahtinov-Bahtinov mask for 400mm f/2 scope?  Thank you!  -Julio

**Comment by satakagi** [comment]
I have no idea too. I only feel empirically that a narrower slit will
produce a clearer diffracted image.
You might consider asking this question on cloudynights.

Satoru

2022年3月20日(日) 3:14 skyjak ***@***.***>:

**Comment by skyjak** [comment]
Thank you Satoru.  Yes, I found examples on Cloudynights of how the slit width affects the diffraction lines. Definitely better the thinner they are.

Regards,
Julio
